spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

user-service:
  base-url: ${USER_SERVICE_URL}

management:
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0.25}

logging:
  level:
    root: INFO
    com.hospital.appointmentservice: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
